language: generic 
sudo: required

services:
  - docker

before_install:
  - docker build -t leonbrown/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true leon.brown/docker-react npm run test -- --coverage